name: ECS Pixi Testing

on:
  push:
    branches:
      - "master"
  pull_request:
  release:
    types:
      - created

jobs:
  pre-commit:
    permissions:
      contents: read
    uses: pcdshub/pcds-ci-helpers/.github/workflows/pre-commit.yml@f74a9345ef8ff8119f76ef087c9222f6000f2610

  unit-tests:
    permissions:
      contents: read
    uses: pcdshub/pcds-ci-helpers/.github/workflows/python-pixi-test.yml@f74a9345ef8ff8119f76ef087c9222f6000f2610

  packaging-tests:
    permissions:
      contents: read
    uses: pcdshub/pcds-ci-helpers/.github/workflows/python-uv-build.yml@f74a9345ef8ff8119f76ef087c9222f6000f2610
    with:
      package-name: "import_name_goes_here"

  pypi-upload:
    permissions:
      id-token: write
    needs: packaging-tests
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    uses: pcdshub/pcds-ci-helpers/.github/workflows/python-uv-publish.yml@f74a9345ef8ff8119f76ef087c9222f6000f2610

  docs-build:
    permissions:
      contents: read
    uses: pcdshub/pcds-ci-helpers/.github/workflows/python-pixi-docs-build.yml@f74a9345ef8ff8119f76ef087c9222f6000f2610

  docs-upload:
    permissions:
      pages: write
      id-token: write
    needs: docs-build
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    uses: pcdshub/pcds-ci-helpers/.github/workflows/docs-upload.yml@f74a9345ef8ff8119f76ef087c9222f6000f2610
