version: ~> 1.0

jobs:
  include:
    - stage: test
      name: "Docs Build (Python 3.8)"
      env:
        - PYTHON_VERSION: 3.8
      workspaces:
        create:
          name: docs
          paths:
            - docs/build/
        use: conda
      install: skip
      before_script:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda config --set always_yes yes --set changeps1 no
        - conda config --set channel_priority strict
        - conda config --remove channels defaults
        - conda config --add channels pcds-tag
        - conda config --add channels conda-forge
        - conda config --add channels "file://`pwd`/bld-dir"
        # Useful for debugging
        - conda info -a
        - conda config --show
        - echo "Conda Environment Name':' ${CONDA_ENV_NAME:=testenv}"
        # Manage conda environment
        - conda create -n ${CONDA_ENV_NAME} python=$PYTHON_VERSION ${CONDA_PACKAGE} ${CONDA_EXTRAS}
        - source activate ${CONDA_ENV_NAME}
        # Useful for debugging
        - conda list

        - echo "Docs Req File':' ${DOCS_REQUIREMENTS:=docs-requirements.txt}"
        - echo "Docs Folder':' ${DOCS_FOLDER:=docs}"
        - |
          # Install docs requirements
          for req in ${DOCS_REQUIREMENTS};
          do
            if [[ ! -f "${req}" ]]; then
                echo "File not found: ${req}" 1>&2
                travis_terminate 1
            else
                pip install --requirement "${req}"
            fi
          done
      script:
        - |
          # Create HTML documentation
          set -e
          pushd ${DOCS_FOLDER}
          make html
          popd
      after_script:
        - set +e
