name: uv publish

# Publish the build outputs from the python-uv-build workflow.
# Assumes that the repo is a trusted publisher on pypi, using a "pypi" environment.

# Note that this workflow cannot be used as-is with trusted publishing.
# This is because of how pypi trusted publishing from github is set up: only a local workflow has the permissions.
# See the example in the repo root and/or copy these workflow steps if you'd like to upload with trusted publishing.

permissions:
  id-token: write

on:
  workflow_call:
    inputs: {}
    outputs: {}

jobs:
  publish-dist:
    runs-on: ubuntu-latest
    environment:
      name: pypi

    defaults:
      run:
        shell: bash

    steps:
    - name: Install uv
      uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9
      with:
        # Lock version to what we use in prod
        version: "0.11.18"

    - name: Download distributions artifact
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
      with:
        name: dist
        path: dist/

    - name: Publish
      run: uv publish
