name: PCDS TwinCAT Standard Tests

on:
  workflow_call:
    inputs:
      project-root:
        required: false
        type: string
        default: "."
        description: "The root directory of the TwinCAT project"
      style-exclude:
        required: false
        type: string
        default: ""
        description: "Pattern (grep) of files to exclude from style checks"
      docs-organization:
        required: false
        type: string
        default: "pcdshub"
        description: "Organization for documentation deployment"
      build-docs:
        required: false
        type: boolean
        default: true
        decription: "Build docs as part of standard (without uploading)"

jobs:
  pre-commit:
    name: "pre-commit checks"
    uses: ./.github/workflows/pre-commit.yml
    secrets: inherit
    with:
      args: "--all-files"

  summary:
    name: "pytmc summary"
    secrets: inherit
    uses: ./.github/workflows/twincat-summary.yml
    with:
      project-root: ${{ inputs.project-root }}

  pragmalint:
    name: "pragma linting"
    secrets: inherit
    uses: ./.github/workflows/twincat-pragmalint.yml
    with:
      project-root: ${{ inputs.project-root }}

  style:
    name: "Style check"
    secrets: inherit
    uses: ./.github/workflows/twincat-style.yml
    with:
      project-root: ${{ inputs.project-root }}
      style-exclude: ${{ inputs.style-exclude }}

  docs:
    name: "Documentation"
    when: ${{ inputs.build-docs }}
    secrets: inherit
    uses: ./.github/workflows/twincat-pixi-docs-build.yml
